/* --------------------------------------------------------------------------
 * scanner_ctl.c - Talks to scanner_axi from Linux, through /dev/mem.
 *
 * The scanner lives in the PL behind an AXI4-Lite interface. This program maps
 * its registers and lets you configure it, start it and read the powers back.
 * No DMA: the stimulus is generated by sig_source INSIDE the PL, so validating
 * the design in silicon needs no data movement, only reading results.
 *
 * It needs root, because /dev/mem needs root.
 *
 *     sudo ./scanner_ctl info
 *     sudo ./scanner_ctl test          <-- the test that matters
 *     sudo ./scanner_ctl run 4000000
 *     sudo ./scanner_ctl dump
 *
 * The default base address is 0xA0000000, which is where the ZynqMP's
 * M_AXI_HPM0_FPD maps the PL's first peripheral. If your bitstream put it
 * somewhere else, pass it as an argument:
 *
 *     sudo ./scanner_ctl --base 0xA0010000 info
 *
 * WHAT `test` PROVES
 *
 * It is the testbench's T5, but in hardware: it tunes some channels onto the
 * two tones sig_source generates and others onto empty band, and checks that
 * the first measure far more power than the second. If that comes out, the
 * scanner really scans, not just in simulation.
 *
 * And it also checks that NOT ONE SAMPLE IS LOST: the PL's sample counter has
 * to match the output counter times CIC_R exactly. A CPU cannot promise that;
 * the PL can, by construction.
 * -------------------------------------------------------------------------- */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <math.h>
#include <time.h>

/* ---- Register map, in byte offsets (see rtl/scanner_axi.v) --------------- */
#define R_ID        0x00
#define R_CTRL      0x04
#define R_SRC_FTWA  0x08
#define R_SRC_FTWB  0x0C
#define R_SRC_SH    0x10
#define R_CFG_CH    0x14
#define R_CFG_FTW   0x18
#define R_PWR_LEN   0x1C
#define R_RD_CH     0x20
#define R_PWR_LO    0x24
#define R_PWR_HI    0x28
#define R_READY     0x2C
#define R_SMP_LO    0x30
#define R_SMP_HI    0x34
#define R_OUT_CNT   0x38
#define R_NCH       0x3C
#define R_TAP_I     0x40
#define R_TAP_Q     0x44

#define CTRL_RUN     (1u << 0)
#define CTRL_SRC_EN  (1u << 1)
#define CTRL_NOISE   (1u << 2)
#define CTRL_CLEAR   (1u << 3)

#define MAGIC       0x5CA44E64u
#define MAP_SIZE    0x1000
#define FS          100000000.0
#define CIC_R       64

/* The tones sig_source puts out by default (see scanner_axi.v). */
#define F_TONE_A    10000000.0
#define F_TONE_B    15000000.0

static volatile uint32_t *regs;

static inline void   wr(int off, uint32_t v) { regs[off / 4] = v; }
static inline uint32_t rd(int off)           { return regs[off / 4]; }

static uint32_t tuning_word(double f_hz)
{
    return (uint32_t)llround((f_hz / FS) * 4294967296.0);
}

static uint64_t read_pwr(int ch)
{
    wr(R_RD_CH, (uint32_t)ch);
    (void)rd(R_RD_CH);                       /* barrier: let the write land */
    uint32_t lo = rd(R_PWR_LO);
    uint32_t hi = rd(R_PWR_HI);
    return ((uint64_t)hi << 32) | lo;
}

static void set_channel(int ch, double f_hz)
{
    wr(R_CFG_CH, (uint32_t)ch);
    wr(R_CFG_FTW, tuning_word(f_hz));        /* writing here fires cfg_we */
}

static double now_s(void)
{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return t.tv_sec + t.tv_nsec * 1e-9;
}

static int map_regs(unsigned long base)
{
    int fd = open("/dev/mem", O_RDWR | O_SYNC);
    if (fd < 0) { perror("/dev/mem (need sudo?)"); return -1; }
    void *p = mmap(NULL, MAP_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED,
                   fd, (off_t)base);
    close(fd);
    if (p == MAP_FAILED) { perror("mmap"); return -1; }
    regs = (volatile uint32_t *)p;
    return 0;
}

static int check_id(void)
{
    uint32_t id = rd(R_ID);
    if (id != MAGIC) {
        fprintf(stderr,
            "ID = 0x%08X, expected 0x%08X.\n"
            "  . is the bitstream loaded?  sudo fpgautil -b scanner64.bit.bin -f Full\n"
            "  . is the base address right?  try --base\n", id, MAGIC);
        return -1;
    }
    return 0;
}

/* Dumps the 32 registers raw. For when something does not add up and you need
 * to see the whole pattern instead of guessing. */
static void cmd_raw(void)
{
    static const char *nm[19] = {
        "ID","CTRL","SRC_FTWA","SRC_FTWB","SRC_SH","CFG_CH","CFG_FTW",
        "PWR_LEN","RD_CH","PWR_LO","PWR_HI","READY","SMP_LO","SMP_HI",
        "OUT_CNT","NCH","TAP_I","TAP_Q","TAP_CNT" };
    printf("\n  off   idx  name         value\n");
    for (int i = 0; i < 20; i++) {
        uint32_t v = rd(i * 4);
        printf("  0x%02X   %2d  %-11s 0x%08X  %u\n",
               i * 4, i, i < 19 ? nm[i] : "-", v, v);
    }
    /* Repeated reads of the same register: if they change, the problem is the
     * handshake and not the address decoding. */
    printf("\n  ID  read 4 times: ");
    for (int i = 0; i < 4; i++) printf("0x%08X ", rd(R_ID));
    printf("\n  NCH read 4 times: ");
    for (int i = 0; i < 4; i++) printf("0x%08X ", rd(R_NCH));
    printf("\n\n");
}

/* Write and read back, to separate three things that look the same from
 * outside: whether writes get through, whether reads return, and whether the
 * scanner processes. Each step rules out one hypothesis. */
static void cmd_probe(void)
{
    printf("\n1) write and read back an RW register\n");
    wr(R_SRC_FTWA, 0xDEADBEEFu);
    uint32_t a = rd(R_SRC_FTWA);
    printf("   SRC_FTWA <- 0xDEADBEEF, read 0x%08X   %s\n",
           a, a == 0xDEADBEEFu ? "WRITE AND READ OK" : "MISMATCH");

    wr(R_PWR_LEN, 1234);
    uint32_t b = rd(R_PWR_LEN);
    printf("   PWR_LEN  <- 1234,       read %u          %s\n",
           b, b == 1234 ? "OK" : "MISMATCH");

    printf("\n2) read-only constant\n");
    printf("   NCH  = %u   (should be 16)\n", rd(R_NCH));
    printf("   ID   = 0x%08X\n", rd(R_ID));

    printf("\n3) start the scanner and see if the counter advances\n");
    wr(R_CTRL, CTRL_RUN);
    uint32_t c1 = rd(R_CTRL);
    printf("   CTRL <- 0x1 (run), read 0x%08X\n", c1);
    wr(R_CTRL, CTRL_RUN | CTRL_SRC_EN);
    uint32_t c2 = rd(R_CTRL);
    printf("   CTRL <- 0x3 (run+src), read 0x%08X\n", c2);

    uint32_t s0 = rd(R_SMP_LO);
    usleep(200000);
    uint32_t s1 = rd(R_SMP_LO);
    printf("   SMP_LO: %u -> %u   (delta %u in 0.2 s)\n", s0, s1, s1 - s0);
    if (s1 != s0) {
        printf("   -> THE SCANNER IS PROCESSING. The PL works.\n");
        printf("      observed rate: %.2f MSPS\n", (s1 - s0) / 0.2 / 1e6);
    } else {
        printf("   -> the counter does not advance: either the generator is not\n");
        printf("      starting or the writes to CTRL are not arriving.\n");
    }
    printf("   OUT_CNT = %u\n", rd(R_OUT_CNT));
    wr(R_CTRL, CTRL_RUN);
    printf("\n");
}

/* Full map of the decoder. When ONLY some registers read correctly there is no
 * point deducing any further: you have to separate two causes that from
 * outside produce exactly the same symptom.
 *
 *   ADDRESS  : the decoder does not answer that offset and falls to default.
 *   SEQUENCE : the handshake returns the data of the PREVIOUS read, so the
 *              value depends on the order you read in, not on where.
 *
 * What we know so far is that 0x00 (ID), 0x10 (SRC_SH) and 0x30 (SMP_LO) read
 * fine -- all three multiples of 16 -- and that the rest return zero. Reading
 * the same 64 words forwards, backwards and twice in a row decides between the
 * two causes in a single pass. */
static void cmd_map(void)
{
    uint32_t asc[64], desc[64], twice[64];
    int i, off, n;
    size_t k;

    for (i = 0; i < 64; i++) asc[i] = rd(i * 4);
    for (i = 63; i >= 0; i--) desc[i] = rd(i * 4);
    for (i = 0; i < 64; i++) { (void)rd(i * 4); twice[i] = rd(i * 4); }

    printf("\n1) the same 64 words, read three ways\n");
    printf("   idx  off    ascending    descending   read twice\n");
    for (i = 0; i < 64; i++) {
        if (!asc[i] && !desc[i] && !twice[i]) continue;
        printf("   %3d  0x%02X   0x%08X   0x%08X   0x%08X%s\n",
               i, i * 4, asc[i], desc[i], twice[i],
               (asc[i] == desc[i] && asc[i] == twice[i]) ? "" : "   <-- CHANGES");
    }
    printf("   (only the ones non-zero in some pass are listed)\n");
    printf("   all three passes equal -> it is the ADDRESS\n");
    printf("   any one CHANGES        -> it is the SEQUENCE (handshake)\n");

    /* If the decoder were shifted, the values would still be there but at some
     * other offset. Searching the whole mapping for them says so without
     * ambiguity: if SRC_FTWA's reset value appears nowhere, then the register
     * really does read zero and it is not a read problem. */
    printf("\n2) where each known value shows up in the 4 KB mapped\n");
    {
        struct { uint32_t v; const char *q; } look[] = {
            { MAGIC,       "ID 0x5CA44E64"           },
            { 0x1999999Au, "SRC_FTWA reset value"    },
            { 0x26666666u, "SRC_FTWB reset value"    },
            { 0x00000022u, "SRC_SH reset value"      },
            { 0x00000400u, "PWR_LEN reset (1024)"    },
            { 0x00000010u, "N_CH = 16"               },
        };
        for (k = 0; k < sizeof look / sizeof look[0]; k++) {
            printf("   %-24s :", look[k].q);
            n = 0;
            for (off = 0; off < 4096; off += 4)
                if (rd(off) == look[k].v && n < 12) { printf(" 0x%03X", off); n++; }
            printf("%s\n", n ? "" : "  APPEARS NOWHERE AT ALL");
        }
    }

    /* And the same from the write side: a different signature into every RW
     * register, then look at where each one landed. */
    printf("\n3) a different signature in each RW register, and a dump\n");
    {
        static const int rw[] = { 0x08, 0x0C, 0x10, 0x14, 0x18, 0x1C, 0x20 };
        int nrw = (int)(sizeof rw / sizeof rw[0]);
        for (i = 0; i < nrw; i++)
            wr(rw[i], 0xC0DE0000u | ((uint32_t)rw[i] << 4) | 0xAu);
        printf("   written:");
        for (i = 0; i < nrw; i++)
            printf(" 0x%02X<-0x%08X", rw[i], 0xC0DE0000u | ((uint32_t)rw[i] << 4) | 0xAu);
        printf("\n   read back (non-zero only):\n");
        for (off = 0; off < 128; off += 4) {
            uint32_t v = rd(off);
            if (v) printf("     0x%02X = 0x%08X\n", off, v);
        }
        printf("   signature in its place  -> write and read OK there\n");
        printf("   signature at ANOTHER offset -> decoder is shifted\n");
        printf("   no signature at all     -> the writes are not arriving\n");
    }

    /* Leave the generator as it was: otherwise the next test comes out odd. */
    wr(R_SRC_FTWA, 0x1999999Au);
    wr(R_SRC_FTWB, 0x26666666u);
    wr(R_SRC_SH,   0x00000022u);
    wr(R_PWR_LEN,  1024u);
    wr(R_CFG_CH,   0u);
    printf("\n");
}

/* ---- Width of the PS's AXI port -----------------------------------------
 *
 * The symptom: only offsets that are multiples of 16 answer (0x00, 0x10, 0x20,
 * 0x30, 0x40) and the rest read zero, while writes DO get through.
 *
 * That is exactly what happens when the master's bus is 128 bits wide and the
 * slave only has 32. Every bus beat carries four words; the slave only drives
 * its own on the first one, and the CPU, reading 0x04, picks up the SECOND
 * word of that beat, which nobody drives -> zero. Reading 0x10 is already a
 * different beat, the CPU picks up the first word, and it comes out right.
 * Writes work because the address travels whole and the slave does not look at
 * wstrb: it takes whatever comes in wdata[31:0].
 *
 * And HPM0_FPD's width is NOT set by the bitstream. It is set by the PS, in
 * FPD_SLCR.AFI_FS (0xFD615000), and that register is written by the FSBL from
 * the project handoff. Loading with `fpgautil` leaves the PS the way the Kria
 * boot left it, which puts both ports at 128 bits. The block design asks for
 * 32. Hence the mismatch.
 *
 *   AFI_FS bits [9:8]   DW_SS0_SEL -> HPM0_FPD
 *          bits [11:10] DW_SS1_SEL -> HPM1_FPD
 *          0 = 32 bits, 1 = 64 bits, 2 = 128 bits
 *
 * `bus` reads it and says so. `bus fix` sets it to 32 bits and dumps the
 * registers again so you can see whether that was it. It is the same thing the
 * FSBL would do. */

#define FPD_SLCR_AFI_FS  0xFD615000UL

static const char *dw_name(unsigned v)
{
    switch (v & 3u) {
    case 0: return "32 bits";
    case 1: return "64 bits";
    case 2: return "128 bits";
    default: return "reserved";
    }
}

static int cmd_bus(int fix)
{
    int fd = open("/dev/mem", O_RDWR | O_SYNC);
    volatile uint32_t *slcr;
    uint32_t v;
    unsigned ss0, ss1;

    if (fd < 0) { perror("/dev/mem"); return 2; }
    slcr = (volatile uint32_t *)mmap(NULL, 0x1000, PROT_READ | PROT_WRITE,
                                     MAP_SHARED, fd, (off_t)FPD_SLCR_AFI_FS);
    close(fd);
    if ((void *)slcr == MAP_FAILED) { perror("mmap FPD_SLCR"); return 2; }

    v   = slcr[0];
    ss0 = (v >> 8) & 3u;
    ss1 = (v >> 10) & 3u;
    printf("\nFPD_SLCR.AFI_FS = 0x%08X\n", v);
    printf("  HPM0_FPD : %s   %s\n", dw_name(ss0),
           ss0 == 0 ? "(what the block design asks for)"
                    : "<-- MISMATCH, the design asks for 32 bits");
    printf("  HPM1_FPD : %s   (off in this design)\n", dw_name(ss1));

    if (ss0 == 0) {
        printf("\n  The width is already right: the fault is something else.\n\n");
        return 0;
    }
    if (!fix) {
        printf("\n  To fix it:  sudo scanner_ctl bus fix\n\n");
        return 1;
    }

    /* Only the four width bits; the rest of the register is left alone. */
    slcr[0] = (v & ~0x00000F00u) | 0x00000000u;
    v = slcr[0];
    printf("\n  written. AFI_FS = 0x%08X -> HPM0_FPD %s\n",
           v, dw_name((v >> 8) & 3u));
    if (((v >> 8) & 3u) != 0) {
        printf("  the register does not accept the write (XMPU?).\n\n");
        return 1;
    }

    printf("\n  and now the scanner registers:\n");
    cmd_raw();
    return 0;
}

/* HPM0_FPD's width is lost on EVERY boot: `fpgautil` loads the PL but does not
 * reconfigure the PS, and the Kria boot leaves both ports at 128 bits.
 * Confirmed in silicon on 14 Sep 2026: with 128 bits only the offsets that
 * were multiples of 16 read correctly and the rest returned zero.
 *
 * That is why it is checked and corrected at the start of every invocation,
 * instead of leaving it to somebody remembering to run `bus fix`. It is
 * exactly what the FSBL would have done had the board booted with this
 * project's handoff. */
static void ensure_bus32(void)
{
    int fd = open("/dev/mem", O_RDWR | O_SYNC);
    volatile uint32_t *slcr;
    uint32_t v;

    if (fd < 0) return;
    slcr = (volatile uint32_t *)mmap(NULL, 0x1000, PROT_READ | PROT_WRITE,
                                     MAP_SHARED, fd, (off_t)FPD_SLCR_AFI_FS);
    close(fd);
    if ((void *)slcr == MAP_FAILED) return;

    v = slcr[0];
    if (((v >> 8) & 3u) != 0) {
        slcr[0] = v & ~0x00000F00u;
        printf("[AFI_FS 0x%08X -> 0x%08X: HPM0_FPD to 32 bits, "
               "which is what the design asks for]\n", v, slcr[0]);
    }
    munmap((void *)slcr, 0x1000);
}

static void cmd_info(void)
{
    printf("\nscanner_axi in the PL\n");
    printf("  ID           : 0x%08X  (OK)\n", rd(R_ID));
    printf("  channels     : %u\n", rd(R_NCH));
    uint32_t c = rd(R_CTRL);
    printf("  CTRL         : 0x%08X  run=%d src=%d noise=%d\n",
           c, !!(c & CTRL_RUN), !!(c & CTRL_SRC_EN), !!(c & CTRL_NOISE));
    printf("  generator    : tone A 0x%08X, tone B 0x%08X, shifts 0x%03X\n",
           rd(R_SRC_FTWA), rd(R_SRC_FTWB), rd(R_SRC_SH) & 0xFFF);
    printf("  pwr window   : %u samples\n", rd(R_PWR_LEN));
    uint64_t smp = ((uint64_t)rd(R_SMP_HI) << 32) | rd(R_SMP_LO);
    printf("  samples      : %llu\n", (unsigned long long)smp);
    printf("  ch0 outputs  : %u\n", rd(R_OUT_CNT));
    printf("  pwr_ready    : 0x%08X\n\n", rd(R_READY));
}

static void cmd_dump(void)
{
    int n = (int)rd(R_NCH);
    printf("\n  channel  power               dBFS approx\n");
    for (int k = 0; k < n; k++) {
        uint64_t p = read_pwr(k);
        uint32_t len = rd(R_PWR_LEN);
        double db = -999.0;
        if (p > 0 && len > 0) {
            /* Mean power per sample, referred to the INPUT full scale, the
             * same as the model's power_db(). */
            double full = 32767.0 * 32767.0;
            db = 10.0 * log10(((double)p / len) / full);
        }
        printf("   %3d    %18llu   %8.2f\n", k, (unsigned long long)p, db);
    }
    printf("\n");
}

static int cmd_run(unsigned long long target_samples)
{
    wr(R_CTRL, CTRL_RUN);                        /* out of reset, stopped */
    wr(R_CTRL, CTRL_RUN | CTRL_CLEAR);
    wr(R_CTRL, CTRL_RUN);
    double t0 = now_s();
    wr(R_CTRL, CTRL_RUN | CTRL_SRC_EN);          /* start the generator */

    uint64_t smp = 0;
    while (smp < target_samples) {
        usleep(20000);
        smp = ((uint64_t)rd(R_SMP_HI) << 32) | rd(R_SMP_LO);
        if (now_s() - t0 > 30.0) break;
    }
    double dt = now_s() - t0;
    wr(R_CTRL, CTRL_RUN);                        /* stop the generator */

    smp = ((uint64_t)rd(R_SMP_HI) << 32) | rd(R_SMP_LO);
    uint32_t out = rd(R_OUT_CNT);

    printf("\n  samples processed   : %llu\n", (unsigned long long)smp);
    printf("  channel 0 outputs   : %u\n", out);
    printf("  time                : %.3f s\n", dt);
    printf("  observed rate       : %.2f MSPS\n", smp / dt / 1e6);

    /* The proof that nothing was lost: out_cnt has to be exactly smp/CIC_R,
     * within a sample or so for the pipeline. */
    long long expect = (long long)(smp / CIC_R);
    long long diff = (long long)out - expect;
    printf("  expected smp/%d     : %lld   (difference %+lld)\n",
           CIC_R, expect, diff);
    if (diff >= -2 && diff <= 2) {
        printf("  -> NOT ONE SAMPLE WAS LOST\n\n");
        return 0;
    }
    printf("  -> MISMATCH: samples have been lost\n\n");
    return 1;
}

static int cmd_test(int n_arg)
{
    /* NCH can be passed by hand: if the register read wrong, there is no
     * reason for the test to be blocked by that. */
    int n = n_arg > 0 ? n_arg : (int)rd(R_NCH);
    if (n < 4) { fprintf(stderr, "at least 4 channels are needed\n"); return 2; }

    printf("\nHardware discrimination test (testbench T5, in silicon)\n");
    printf("  The PL generator emits two tones: %.0f and %.0f MHz.\n",
           F_TONE_A / 1e6, F_TONE_B / 1e6);

    wr(R_CTRL, CTRL_RUN);
    /* Program the generator EXPLICITLY. Do not trust the reset values: any
     * earlier test may have left them disturbed, and then this test hunts for
     * tones where there are none and fails for nothing. */
    wr(R_SRC_FTWA, tuning_word(F_TONE_A));
    wr(R_SRC_FTWB, tuning_word(F_TONE_B));
    wr(R_SRC_SH,   0x022);
    wr(R_PWR_LEN, 4096);

    /* Half the channels onto the tones, half onto empty band. */
    double freqs[64];
    int occupied[64];
    for (int k = 0; k < n && k < 64; k++) {
        if (k % 4 == 0)      { freqs[k] = F_TONE_A;            occupied[k] = 1; }
        else if (k % 4 == 1) { freqs[k] = F_TONE_B;            occupied[k] = 1; }
        else if (k % 4 == 2) { freqs[k] = 22000000.0 + k*1e5;  occupied[k] = 0; }
        else                 { freqs[k] =  3000000.0 + k*1e5;  occupied[k] = 0; }
        set_channel(k, freqs[k]);
    }

    wr(R_CTRL, CTRL_RUN | CTRL_CLEAR);
    wr(R_CTRL, CTRL_RUN | CTRL_SRC_EN);
    usleep(300000);                              /* let several windows fill */
    wr(R_CTRL, CTRL_RUN);

    double min_occ = 1e300, max_emp = 0.0;
    printf("\n  channel  tuning        power               state\n");
    for (int k = 0; k < n && k < 64; k++) {
        uint64_t p = read_pwr(k);
        printf("   %3d   %6.1f MHz   %18llu   %s\n",
               k, freqs[k] / 1e6, (unsigned long long)p,
               occupied[k] ? "TONE" : "empty");
        if (occupied[k]) { if ((double)p < min_occ) min_occ = (double)p; }
        else             { if ((double)p > max_emp) max_emp = (double)p; }
    }

    printf("\n  lowest of the occupied : %.0f\n", min_occ);
    printf("  highest of the empty   : %.0f\n", max_emp);
    if (max_emp <= 0.0) max_emp = 1.0;
    double ratio = min_occ / max_emp;
    printf("  margin                 : x%.0f  (%.1f dB)\n",
           ratio, 10.0 * log10(ratio));

    uint32_t ready = rd(R_READY);
    printf("  pwr_ready              : 0x%08X\n\n", ready);

    if (ratio > 100.0) {
        printf("RESULT: PASS - the scanner discriminates IN HARDWARE.\n\n");
        return 0;
    }
    printf("RESULT: FAIL - there is not enough margin.\n\n");
    return 1;
}

/* A DETERMINISTIC measurement, to check it against the model bit for bit.
 *
 * First attempt: measure the first power window after reset. IT DOES NOT WORK,
 * and the reason is written in rtl/comb_bank.v: the comb state lives in
 * distributed LUTRAM and is initialised by `initial`, that is, by the
 * bitstream. A warm reset does NOT clear it. The integrators do go back to
 * zero, the combs drag along the state from the previous test, and the first
 * outputs are garbage -- large garbage, because the comb subtracts an
 * unrelated state and saturates. A couple of full-scale samples swallow a
 * window of 4096. That is the price of saving 7001 flip-flops, and it is
 * accepted.
 *
 * So the power window is not used: the TAPs are. `tap_i`/`tap_q` freeze the
 * LAST output of the selected channel and `out_cnt` says which one it is.
 * Reading the triple (index, I, Q) gives an exact point on the signal, without
 * depending on where any window starts:
 *
 *   - `run` low leaves the integrators at zero and the NCOs at phase zero, and
 *     each channel's NCO only advances with in_valid, so the sequence is
 *     reproducible cycle for cycle from the very first sample.
 *   - the dirty comb state clears in three rounds; measuring from output ~3000
 *     onwards, whatever is inside was put there long ago by the samples of
 *     THIS run, which are the same ones the model sees.
 *   - and there is no index to guess: it is read.
 *
 * One channel per run, because out_cnt counts the outputs of the channel
 * pointed at by rd_ch. */
static int cmd_golden(void)
{
    static const double freqs[4] = { F_TONE_A, F_TONE_B, 22200000.0, 3300000.0 };
    uint32_t cnt[4];
    int32_t  ti[4], tq[4];
    int k;

    if ((int)rd(R_NCH) < 4) { fprintf(stderr, "4 channels are needed\n"); return 2; }

    for (k = 0; k < 4; k++) {
        wr(R_CTRL, 0);                          /* reset: integrators and NCO */
        usleep(1000);
        wr(R_CTRL, CTRL_RUN);                   /* out of reset, stopped */

        wr(R_SRC_FTWA, tuning_word(F_TONE_A));
        wr(R_SRC_FTWB, tuning_word(F_TONE_B));
        wr(R_SRC_SH,   0x022);
        wr(R_PWR_LEN,  4096);
        set_channel(k, freqs[k]);               /* tuning comes AFTER run */
        wr(R_RD_CH, (uint32_t)k);               /* tap_ch follows rd_ch */

        wr(R_CTRL, CTRL_RUN | CTRL_SRC_EN);     /* start the sequence */
        usleep(2000);                           /* ~200k samples, ~3000 outputs */
        wr(R_CTRL, CTRL_RUN);                   /* freeze the tap */

        cnt[k] = rd(R_OUT_CNT);
        ti[k]  = (int32_t)rd(R_TAP_I);
        tq[k]  = (int32_t)rd(R_TAP_Q);
    }

    printf("\nExact points on the signal, one per channel\n\n");
    printf("  channel  tuning        output no.     I          Q\n");
    for (k = 0; k < 4; k++)
        printf("   %3d   %6.1f MHz   %9u   %8d   %8d\n",
               k, freqs[k] / 1e6, cnt[k], ti[k], tq[k]);

    printf("\n  Check it against the model, right here on the board:\n"
           "\n    python3 ~/scanner64/model/golden_hw.py");
    for (k = 0; k < 4; k++)
        printf(" %u %d %d", cnt[k], ti[k], tq[k]);
    printf("\n\n");
    return 0;
}

/* How much reading over AXI-Lite is actually worth, measured instead of
 * estimated.
 *
 * An expensive decision hangs on this: variant (b) of METODOLOGIA.md -- the
 * FPGA generates and the ARM consumes -- needs the samples moved from the PL
 * to the PS. If AXI-Lite has plenty of headroom, a FIFO and a handful of
 * registers are enough, and those are nearly there already. If it does not
 * reach, it needs DMA through an HP port: new block design, new bitstream and
 * buffer management.
 *
 * The measurement is the time of one 32-bit read against device memory. There,
 * every read is a complete round trip across the interconnect: no cache to
 * absorb it and no pipeline to overlap it, which is exactly what makes it
 * expensive and what has to be quantified.
 *
 * Reading CONSECUTIVE words is measured too. If the compiler or the bus manage
 * to overlap them, the useful rate goes up; if not, every read pays its full
 * latency. */
static void cmd_rate(void)
{
    const int N = 200000;
    volatile uint32_t sink = 0;
    double t0, dt;
    int i;

    printf("\nAXI-Lite reads from user space\n\n");

    /* 1) The same register, over and over. */
    t0 = now_s();
    for (i = 0; i < N; i++) sink += rd(R_ID);
    dt = now_s() - t0;
    double one = N / dt;
    printf("  one register, %d reads : %6.0f ns each, %5.2f M reads/s\n",
           N, dt / N * 1e9, one / 1e6);

    /* 2) Consecutive words, in case they overlap. */
    t0 = now_s();
    for (i = 0; i < N; i += 4) {
        sink += rd(R_SMP_LO);
        sink += rd(R_SMP_HI);
        sink += rd(R_OUT_CNT);
        sink += rd(R_NCH);
    }
    dt = now_s() - t0;
    double seq = N / dt;
    printf("  4 consecutive          : %6.0f ns each, %5.2f M reads/s\n",
           dt / N * 1e9, seq / 1e6);

    double best = one > seq ? one : seq;
    (void)sink;

    /* With 16-bit samples, two fit per 32-bit word. */
    double msps = best * 2.0 / 1e6;
    printf("\n  Packing 2 16-bit samples per word:\n");
    printf("    transport ceiling     : %.2f MSPS\n", msps);

    /* And what the A53 can consume: 157.7 M channel-samples/s on 4 threads,
     * shared out between however many channels there are. */
    printf("\n  Against what the four A53 can process (157.7 M cs/s):\n");
    printf("    channels  needs       transport     verdict\n");
    for (i = 4; i <= 64; i *= 2) {
        double needs = 157.7e6 / i / 1e6;
        printf("    %5d    %6.2f MSPS  %6.2f MSPS   %s\n",
               i, needs, msps,
               msps >= needs ? "a FIFO is enough" : "DMA is needed");
    }
    printf("\n");
}

/* Start and stop without leaving anything running.
 *
 * `run` blocks until it finishes, and killing it halfway leaves the generator
 * on -- exactly what contaminates the next phase of an alternating
 * measurement. With these two, the script drives the scanner and nothing else
 * stays alive. */
static void cmd_start(void)
{
    wr(R_CTRL, CTRL_RUN);
    wr(R_CTRL, CTRL_RUN | CTRL_SRC_EN);
}

static void cmd_stop(void)
{
    wr(R_CTRL, CTRL_RUN);            /* out of reset, generator stopped */
}

int main(int argc, char **argv)
{
    unsigned long base = 0xA0000000UL;
    int a = 1;
    if (argc > 2 && !strcmp(argv[1], "--base")) {
        base = strtoul(argv[2], NULL, 0);
        a = 3;
    }
    if (a >= argc) {
        fprintf(stderr,
            "usage: %s [--base 0xA0000000] {info|raw|probe|map|bus [fix]|test [N]|golden|rate|start|stop|run N|dump}\n", argv[0]);
        return 2;
    }
    ensure_bus32();
    if (map_regs(base) != 0) return 2;
    if (check_id() != 0) return 2;

    if (!strcmp(argv[a], "info")) { cmd_info(); return 0; }
    if (!strcmp(argv[a], "dump")) { cmd_dump(); return 0; }
    if (!strcmp(argv[a], "golden")) return cmd_golden();
    if (!strcmp(argv[a], "rate"))   { cmd_rate();   return 0; }
    if (!strcmp(argv[a], "start"))  { cmd_start();  return 0; }
    if (!strcmp(argv[a], "stop"))   { cmd_stop();   return 0; }
    if (!strcmp(argv[a], "raw"))   { cmd_raw();   return 0; }
    if (!strcmp(argv[a], "probe")) { cmd_probe(); return 0; }
    if (!strcmp(argv[a], "map"))   { cmd_map();   return 0; }
    if (!strcmp(argv[a], "bus"))
        return cmd_bus((a + 1 < argc) && !strcmp(argv[a+1], "fix"));
    if (!strcmp(argv[a], "test")) {
        int nc = (a + 1 < argc) ? atoi(argv[a+1]) : 0;
        return cmd_test(nc);
    }
    if (!strcmp(argv[a], "run")) {
        unsigned long long n = (a + 1 < argc) ? strtoull(argv[a+1], NULL, 0)
                                              : 100000000ULL;
        return cmd_run(n);
    }
    fprintf(stderr, "unknown command: %s\n", argv[a]);
    return 2;
}
