#!/usr/bin/env python3
"""
Generates the files the RTL and its testbench consume, from the bit-exact
model in ddc_model.py.

Outputs:
    rtl/sin_lut.mem        cosine LUT for $readmemh (the NCO BRAM)
    tb/vectors/stim.hex    input samples, IN_W bits, signed hex
    tb/vectors/gold_i.hex  expected I output, OUT_W bits
    tb/vectors/gold_q.hex  expected Q output, OUT_W bits
    tb/vectors/params.vh   parameters and the tuning word used

Since the testbench compares against these vectors, if the RTL is correctly
transcribed the simulation passes without tweaking anything. If it fails, the
RTL differs from the model - and the model is verified (see ddc_model.py).

Usage:
    py gen_vectors.py
"""

import math
import os

from ddc_model import (
    DDCChannel, SIN_LUT, tuning_word,
    IN_W, OUT_W, PHASE_W, LUT_ADDR_W, LUT_W, MIX_W,
    CIC_N, CIC_R, CIC_M, CIC_W, CIC_GROWTH,
)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RTL = os.path.join(ROOT, "rtl")
VEC = os.path.join(ROOT, "tb", "vectors")

# Test scenario: two tones, one inside the channel and one outside.
FS      = 100_000_000.0
F_TUNE  =  10_000_000.0     # tuned channel
F_IN    =  10_000_000.0     # in-band tone
F_OUT   =  15_000_000.0     # out-of-band tone (should be rejected)
AMP_IN  = 0.40
AMP_OUT = 0.40
N_OUT   = 48                # output samples to check
N_IN    = N_OUT * CIC_R


def twos_hex(value, bits):
    """Signed integer -> `bits`-bit hex, no prefix."""
    return f"{value & ((1 << bits) - 1):0{(bits + 3) // 4}x}"


def write_lines(path, lines, header=None):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as fh:
        if header:
            for h in header:
                fh.write(f"// {h}\n")
        fh.write("\n".join(lines))
        fh.write("\n")
    print(f"  {os.path.relpath(path, ROOT):28} {len(lines):5d} lines")


def main():
    print("Generating files for the RTL from the verified model")
    print()

    # --- NCO LUT -------------------------------------------------------
    write_lines(
        os.path.join(RTL, "sin_lut.mem"),
        [twos_hex(v, LUT_W) for v in SIN_LUT],
    )

    # --- Stimulus: the sum of both tones --------------------------------
    peak = (1 << (IN_W - 1)) - 1
    stim = []
    for k in range(N_IN):
        s = (AMP_IN * peak * math.sin(2 * math.pi * F_IN * k / FS)
             + AMP_OUT * peak * math.sin(2 * math.pi * F_OUT * k / FS))
        # Saturate in case the sum goes past full scale.
        stim.append(max(-peak - 1, min(peak, int(round(s)))))

    write_lines(os.path.join(VEC, "stim.hex"),
                [twos_hex(v, IN_W) for v in stim])

    # --- Expected output, from the bit-exact model ----------------------
    ch = DDCChannel(F_TUNE, FS)
    gold = [y for y in (ch.push(x) for x in stim) if y is not None]

    write_lines(os.path.join(VEC, "gold_i.hex"),
                [twos_hex(i, OUT_W) for i, _ in gold])
    write_lines(os.path.join(VEC, "gold_q.hex"),
                [twos_hex(q, OUT_W) for _, q in gold])

    # --- Parameters for the testbench -----------------------------------
    ftw = tuning_word(F_TUNE, FS)
    params = [
        "// Generated by model/gen_vectors.py - do not edit by hand.",
        "",
        f"localparam integer P_IN_W       = {IN_W};",
        f"localparam integer P_OUT_W      = {OUT_W};",
        f"localparam integer P_PHASE_W    = {PHASE_W};",
        f"localparam integer P_LUT_ADDR_W = {LUT_ADDR_W};",
        f"localparam integer P_LUT_W      = {LUT_W};",
        f"localparam integer P_MIX_W      = {MIX_W};",
        f"localparam integer P_CIC_N      = {CIC_N};",
        f"localparam integer P_CIC_R      = {CIC_R};",
        f"localparam integer P_CIC_M      = {CIC_M};",
        f"localparam integer P_CIC_W      = {CIC_W};",
        f"localparam integer P_CIC_GROWTH = {CIC_GROWTH};",
        "",
        f"localparam [P_PHASE_W-1:0] P_FTW = {PHASE_W}'h{ftw:08x};  // {F_TUNE/1e6:.3f} MHz @ {FS/1e6:.0f} MSPS",
        f"localparam integer P_N_STIM = {len(stim)};",
        f"localparam integer P_N_GOLD = {len(gold)};",
    ]
    write_lines(os.path.join(VEC, "params.vh"), params)

    # --- Summary ---------------------------------------------------------
    from ddc_model import power_db
    steady = gold[8:]
    p = sum(power_db(i, q) for i, q in steady) / len(steady)
    expected = 20 * math.log10(AMP_IN / 2)
    print()
    print(f"  Scenario: in-band tone {F_IN/1e6:.0f} MHz (A={AMP_IN}) + "
          f"out-of-band tone {F_OUT/1e6:.0f} MHz (A={AMP_OUT})")
    print(f"  Power measured in the channel: {p:.2f} dBFS "
          f"(theoretical with the in-band tone alone: {expected:.2f} dBFS)")
    if abs(p - expected) < 1.0:
        print("  -> the out-of-band tone is rejected. Vectors valid.")
    else:
        print("  -> WARNING: the out-of-band tone is not sufficiently rejected")


if __name__ == "__main__":
    main()
