#!/usr/bin/env python3
"""
Generates the golden vectors for the channel BANK (scanner_top), from the same
bit-exact model that already validates a single channel.

What the bank tests and the channel does not:
    - that N channels with different tunings do not step on each other
    - that cfg_we writes the tuning word into the right channel
    - that the power meter accumulates, freezes and restarts properly
    - that the scanner really does DISCRIMINATE: channels tuned to a tone
      measure high power and those tuned to empty band measure low

Scenario: the input carries two tones (10 and 15 MHz). Four channels are tuned,
two onto the tones and two onto empty bands.

Outputs:
    tb/vectors/bank_ftw.hex      N_CH tuning words
    tb/vectors/bank_gold.hex     expected I and Q, in per-channel blocks
    tb/vectors/bank_pwr.hex      expected rd_pwr value per channel
    tb/vectors/params_bank.vh    parameters for the bank testbench

Reuses stim.hex, which gen_vectors.py produces. Run that one first.

Usage:
    py gen_vectors_bank.py
"""

import math
import os

from ddc_model import (
    DDCChannel, tuning_word, power_db,
    IN_W, OUT_W, PHASE_W, CIC_R,
)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VEC = os.path.join(ROOT, "tb", "vectors")

FS = 100_000_000.0

# Tones present in the stimulus (the same ones gen_vectors.py produces).
F_IN = 10_000_000.0
F_OUT = 15_000_000.0
AMP_IN = 0.40
AMP_OUT = 0.40

# Bank tunings. Two onto the tones, two onto empty bands.
TUNES = [
    (10_000_000.0, "tone A, in band"),
    (15_000_000.0, "tone B, the one channel 0 rejects"),
    (20_000_000.0, "empty"),
    (5_000_000.0, "empty"),
]
N_CH = len(TUNES)

PWR_LEN = 16                 # samples per measurement window
N_OUT = 48                   # outputs per channel, as in the single channel
N_IN = N_OUT * CIC_R
PWR_W = 48


def twos_hex(value, bits):
    return f"{value & ((1 << bits) - 1):0{(bits + 3) // 4}x}"


def write_lines(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines))
        fh.write("\n")
    print(f"  {os.path.relpath(path, ROOT):32} {len(lines):6d} lines")


def make_stim():
    """The same stimulus as gen_vectors.py: two tones summed and saturated."""
    peak = (1 << (IN_W - 1)) - 1
    out = []
    for k in range(N_IN):
        s = (AMP_IN * peak * math.sin(2 * math.pi * F_IN * k / FS)
             + AMP_OUT * peak * math.sin(2 * math.pi * F_OUT * k / FS))
        out.append(max(-peak - 1, min(peak, int(round(s)))))
    return out


def expected_power(gold):
    """Replicates EXACTLY the arithmetic of the scanner_top power meter.

    The RTL freezes the sum of PWR_LEN samples into pwr_hold and restarts. What
    you read at the end through rd_pwr is the last complete window, not the
    total.
    """
    acc = cnt = hold = 0
    done = False
    for i, q in gold:
        mag2 = i * i + q * q
        if cnt + 1 >= PWR_LEN:
            hold = (acc + mag2) & ((1 << PWR_W) - 1)
            acc = 0
            cnt = 0
            done = True
        else:
            acc += mag2
            cnt += 1
    return hold, done


def main():
    print("Generating bank vectors from the verified model")
    print()

    stim = make_stim()

    gold_per_ch = []
    pwr_per_ch = []
    for f_tune, _ in TUNES:
        ch = DDCChannel(f_tune, FS)
        gold = [y for y in (ch.push(x) for x in stim) if y is not None]
        assert len(gold) == N_OUT, f"expected {N_OUT} outputs, got {len(gold)}"
        gold_per_ch.append(gold)
        hold, done = expected_power(gold)
        assert done, "PWR_LEN larger than the number of outputs: no window closes"
        pwr_per_ch.append(hold)

    # --- Tunings -------------------------------------------------------
    write_lines(os.path.join(VEC, "bank_ftw.hex"),
                [twos_hex(tuning_word(f, FS), PHASE_W) for f, _ in TUNES])

    # --- Golden vectors, in per-channel blocks --------------------------
    # Channel k occupies [k*N_OUT, (k+1)*N_OUT). A single $readmemh in the
    # testbench, because $readmemh needs a constant file name.
    lines_i, lines_q = [], []
    for gold in gold_per_ch:
        lines_i += [twos_hex(i, OUT_W) for i, _ in gold]
        lines_q += [twos_hex(q, OUT_W) for _, q in gold]
    write_lines(os.path.join(VEC, "bank_gold_i.hex"), lines_i)
    write_lines(os.path.join(VEC, "bank_gold_q.hex"), lines_q)

    # --- Expected power -------------------------------------------------
    write_lines(os.path.join(VEC, "bank_pwr.hex"),
                [twos_hex(p, PWR_W) for p in pwr_per_ch])

    # --- Parameters ------------------------------------------------------
    params = [
        "// Generated by model/gen_vectors_bank.py - do not edit by hand.",
        "",
        f"localparam integer PB_N_CH    = {N_CH};",
        f"localparam integer PB_N_STIM  = {len(stim)};",
        f"localparam integer PB_N_GOLD  = {N_OUT};",
        f"localparam integer PB_PWR_LEN = {PWR_LEN};",
        f"localparam integer PB_PWR_W   = {PWR_W};",
    ]
    write_lines(os.path.join(VEC, "params_bank.vh"), params)

    # --- Summary: check the scenario really does discriminate ------------
    print()
    print("  Channel  tuning       mean steady-state power    scenario")
    steady_db = []
    for k, (f_tune, note) in enumerate(TUNES):
        steady = gold_per_ch[k][8:]
        p = sum(power_db(i, q) for i, q in steady) / len(steady)
        steady_db.append(p)
        print(f"    {k}    {f_tune/1e6:5.1f} MHz    {p:9.2f} dBFS            {note}")

    occupied = min(steady_db[0], steady_db[1])
    empty = max(steady_db[2], steady_db[3])
    margin = occupied - empty
    print()
    print(f"  Margin between channels with a tone and empty channels: {margin:.1f} dB")
    if margin > 40.0:
        print("  -> the bank discriminates. Vectors valid.")
    else:
        print("  -> WARNING: insufficient margin, the discrimination test is worthless")


if __name__ == "__main__":
    main()
