// Generated by model/gen_vectors_bank.py - do not edit by hand.

localparam integer PB_N_CH    = 4;
localparam integer PB_N_STIM  = 3072;
localparam integer PB_N_GOLD  = 48;
localparam integer PB_PWR_LEN = 16;
localparam integer PB_PWR_W   = 48;
