// ---------------------------------------------------------------------------
// tb_scanner_top.v - Self-checking testbench for the channel BANK.
//
// The channel testbench (tb_ddc_channel) tests the arithmetic. This one tests
// what only shows up once you put N channels together, which is where the bugs
// the other one cannot see live:
//
//   T1  cfg_we writes the tuning into the given channel, and ONLY that one.
//   T2  the N channels all produce at once and each gives its own result: none
//       steps on another despite sharing clk, rst and the input stream.
//   T3  the tap_ch mux returns the selected channel.
//   T4  the power meter accumulates, freezes and restarts; rd_ch reads right.
//   T5  the scanner DISCRIMINATES: channels on a tone measure high power and
//       those tuned to empty band measure low. This is the proof it is useful.
//   T6  cfg_clear resets the accumulators.
//
// Golden vectors from model/gen_vectors_bank.py, taken from the same bit-exact
// model that validates the single channel.
//
// Run with XSim:
//     xvlog -sv -i vectors ../rtl/nco.v ../rtl/cic_decim.v \
//                          ../rtl/ddc_channel.v ../rtl/scanner_top.v \
//                          ../tb/tb_scanner_top.v
//     xelab tb_scanner_top -s tb_bank
//     xsim tb_bank -runall
//
// Run with iverilog:
//     iverilog -g2012 -o tb_bank.vvp -I vectors \
//         tb/tb_scanner_top.v rtl/nco.v rtl/cic_decim.v rtl/ddc_channel.v \
//         rtl/scanner_top.v
//     vvp tb_bank.vvp
//
// The LUT .mem file and the vectors/ directory have to be in the simulator's
// working directory: the $readmemh uses paths relative to it.
// ---------------------------------------------------------------------------

`timescale 1ns / 1ps
`default_nettype none

module tb_scanner_top;

    `include "params.vh"          // generated by model/gen_vectors.py
    `include "params_bank.vh"     // generated by model/gen_vectors_bank.py

    localparam integer SKIP  = 8;                  // CIC transient
    localparam integer CH_W  = $clog2(PB_N_CH);
    localparam integer DISCR = 1000;               // T5 minimum margin, times

    reg clk = 1'b0;
    reg rst_n = 1'b0;
    always #5 clk = ~clk;         // 100 MHz

    // ---- Vectors -----------------------------------------------------------
    reg signed [P_IN_W-1:0]  stim     [0:PB_N_STIM-1];
    reg        [P_PHASE_W-1:0] ftw_v  [0:PB_N_CH-1];
    reg signed [P_OUT_W-1:0] gold_i   [0:PB_N_CH*PB_N_GOLD-1];
    reg signed [P_OUT_W-1:0] gold_q   [0:PB_N_CH*PB_N_GOLD-1];
    reg        [PB_PWR_W-1:0] gold_pwr[0:PB_N_CH-1];

    initial begin
        $readmemh("vectors/stim.hex",        stim);
        $readmemh("vectors/bank_ftw.hex",    ftw_v);
        $readmemh("vectors/bank_gold_i.hex", gold_i);
        $readmemh("vectors/bank_gold_q.hex", gold_q);
        $readmemh("vectors/bank_pwr.hex",    gold_pwr);
    end

    // ---- Unit under test ---------------------------------------------------
    reg                       in_valid = 1'b0;
    reg signed [P_IN_W-1:0]   in_data  = {P_IN_W{1'b0}};

    reg                       cfg_we      = 1'b0;
    reg  [CH_W-1:0]           cfg_ch      = {CH_W{1'b0}};
    reg  [P_PHASE_W-1:0]      cfg_ftw     = {P_PHASE_W{1'b0}};
    reg  [31:0]               cfg_pwr_len = PB_PWR_LEN;
    reg                       cfg_clear   = 1'b0;

    reg  [CH_W-1:0]           rd_ch  = {CH_W{1'b0}};
    reg  [CH_W-1:0]           tap_ch = {CH_W{1'b0}};

    wire [PB_PWR_W-1:0]       rd_pwr;
    wire [PB_N_CH-1:0]        pwr_ready;
    wire                      tap_valid;
    wire signed [P_OUT_W-1:0] tap_i, tap_q;

    scanner_top #(
        .N_CH (PB_N_CH),
        .IN_W (P_IN_W), .OUT_W (P_OUT_W), .PHASE_W (P_PHASE_W),
        .LUT_ADDR_W (P_LUT_ADDR_W), .LUT_W (P_LUT_W), .MIX_W (P_MIX_W),
        .CIC_N (P_CIC_N), .CIC_R (P_CIC_R), .CIC_W (P_CIC_W),
        .CIC_GROWTH (P_CIC_GROWTH), .PWR_W (PB_PWR_W),
        .LUT_FILE ("sin_lut.mem")
    ) dut (
        .clk (clk), .rst_n (rst_n),
        .in_valid (in_valid), .in_data (in_data),
        .cfg_we (cfg_we), .cfg_ch (cfg_ch), .cfg_ftw (cfg_ftw),
        .cfg_pwr_len (cfg_pwr_len), .cfg_clear (cfg_clear),
        .rd_ch (rd_ch), .rd_pwr (rd_pwr), .pwr_ready (pwr_ready),
        .tap_ch (tap_ch), .tap_valid (tap_valid),
        .tap_i (tap_i), .tap_q (tap_q)
    );

    // ---- Error counters, one per test --------------------------------------
    integer e_cfg    = 0;   // T1
    integer e_out    = 0;   // T2, in steady state
    integer e_trans  = 0;   // T2, during the transient (informational)
    integer e_tap    = 0;   // T3
    integer e_pwr    = 0;   // T4
    integer e_discr  = 0;   // T5
    integer e_clear  = 0;   // T6
    integer checked  = 0;

    // ---- T2: comparing the N channels, sample by sample --------------------
    // With shared combs the channels do NOT come out on the same cycle any
    // more: each one comes out on its turn within the round. So each channel
    // carries its own output counter and gets compared when ITS ch_valid goes
    // high.
    integer oi_ch [0:PB_N_CH-1];
    integer oi = 0;
    integer c;

    initial for (c = 0; c < PB_N_CH; c = c + 1) oi_ch[c] = 0;

    always @(posedge clk) begin
        if (rst_n) begin
            for (c = 0; c < PB_N_CH; c = c + 1) begin
                if (dut.ch_valid[c]) begin
                    if (oi_ch[c] < PB_N_GOLD) begin
                        if (dut.ch_i[c] !== gold_i[c*PB_N_GOLD + oi_ch[c]] ||
                            dut.ch_q[c] !== gold_q[c*PB_N_GOLD + oi_ch[c]]) begin
                            if (oi_ch[c] >= SKIP) begin
                                e_out = e_out + 1;
                                if (e_out <= 10)
                                    $display("  T2 ch%0d [%0d] expected I=%0d Q=%0d   rtl I=%0d Q=%0d",
                                             c, oi_ch[c],
                                             gold_i[c*PB_N_GOLD + oi_ch[c]],
                                             gold_q[c*PB_N_GOLD + oi_ch[c]],
                                             dut.ch_i[c], dut.ch_q[c]);
                            end else begin
                                e_trans = e_trans + 1;
                            end
                        end
                        if (oi_ch[c] >= SKIP) checked = checked + 1;
                    end
                    oi_ch[c] = oi_ch[c] + 1;
                    if (c == 0) oi = oi_ch[0];
                end
            end
        end
    end

    // ---- Main sequence -----------------------------------------------------
    integer si, k;
    reg [PB_PWR_W-1:0] pwr_rd [0:PB_N_CH-1];

    initial begin
        repeat (4) @(posedge clk);
        rst_n <= 1'b1;
        @(posedge clk);

        // --- T1: write a different tuning into every channel ----------------
        for (k = 0; k < PB_N_CH; k = k + 1) begin
            cfg_we  <= 1'b1;
            cfg_ch  <= k[CH_W-1:0];
            cfg_ftw <= ftw_v[k];
            @(posedge clk);
        end
        cfg_we <= 1'b0;
        @(posedge clk);

        for (k = 0; k < PB_N_CH; k = k + 1)
            if (dut.ftw[k] !== ftw_v[k]) begin
                e_cfg = e_cfg + 1;
                $display("  T1 ch%0d tuning expected %08x, read %08x",
                         k, ftw_v[k], dut.ftw[k]);
            end

        // --- T2: push the stimulus through ----------------------------------
        for (si = 0; si < PB_N_STIM; si = si + 1) begin
            in_valid <= 1'b1;
            in_data  <= stim[si];
            @(posedge clk);
        end
        in_valid <= 1'b0;
        repeat (200) @(posedge clk);   // flush the pipeline

        // --- T3: the tap_ch mux ---------------------------------------------
        // With in_valid low the outputs stay frozen, so tap_ch can be swept
        // and compared against the corresponding channel.
        for (k = 0; k < PB_N_CH; k = k + 1) begin
            tap_ch = k[CH_W-1:0];
            #1;
            if (tap_i !== dut.ch_i[k] || tap_q !== dut.ch_q[k]) begin
                e_tap = e_tap + 1;
                $display("  T3 tap_ch=%0d returns I=%0d Q=%0d, the channel holds I=%0d Q=%0d",
                         k, tap_i, tap_q, dut.ch_i[k], dut.ch_q[k]);
            end
        end

        // --- T4: power per channel ------------------------------------------
        for (k = 0; k < PB_N_CH; k = k + 1) begin
            rd_ch = k[CH_W-1:0];
            #1;
            pwr_rd[k] = rd_pwr;
            if (rd_pwr !== gold_pwr[k]) begin
                e_pwr = e_pwr + 1;
                $display("  T4 ch%0d power expected %0d, read %0d",
                         k, gold_pwr[k], rd_pwr);
            end
            if (pwr_ready[k] !== 1'b1) begin
                e_pwr = e_pwr + 1;
                $display("  T4 ch%0d pwr_ready still 0 after %0d complete windows",
                         k, PB_N_GOLD / PB_PWR_LEN);
            end
        end

        // --- T5: discrimination ----------------------------------------------
        // Channels 0 and 1 sit on a tone; 2 and 3, on empty band.
        for (k = 0; k < 2; k = k + 1) begin
            for (c = 2; c < PB_N_CH; c = c + 1) begin
                if (pwr_rd[k] < pwr_rd[c] * DISCR) begin
                    e_discr = e_discr + 1;
                    $display("  T5 channel %0d (with tone, %0d) does not beat channel %0d (empty, %0d) by %0dx",
                             k, pwr_rd[k], c, pwr_rd[c], DISCR);
                end
            end
        end

        // --- T6: cfg_clear ---------------------------------------------------
        cfg_clear <= 1'b1;
        @(posedge clk);
        cfg_clear <= 1'b0;
        @(posedge clk);
        #1;
        if (pwr_ready !== {PB_N_CH{1'b0}}) begin
            e_clear = e_clear + 1;
            $display("  T6 pwr_ready does not clear on cfg_clear: %b", pwr_ready);
        end
        for (k = 0; k < PB_N_CH; k = k + 1) begin
            rd_ch = k[CH_W-1:0];
            #1;
            if (rd_pwr !== {PB_PWR_W{1'b0}}) begin
                e_clear = e_clear + 1;
                $display("  T6 ch%0d rd_pwr does not clear on cfg_clear: %0d", k, rd_pwr);
            end
        end

        report_and_finish;
    end

    // ---- Report ------------------------------------------------------------
    integer total;
    task report_and_finish;
        begin
            total = e_cfg + e_out + e_tap + e_pwr + e_discr + e_clear;
            $display("");
            $display("tb_scanner_top   (%0d channels, %0d outputs per channel)", PB_N_CH, PB_N_GOLD);
            $display("  outputs produced : %0d", oi);
            $display("  compared         : %0d  (%0d channels x %0d steady-state samples)",
                     checked, PB_N_CH, PB_N_GOLD - SKIP);
            $display("");
            $display("  T1 tunings             : %0d failures", e_cfg);
            $display("  T2 channels not mixing : %0d failures", e_out);
            $display("  T3 tap_ch mux          : %0d failures", e_tap);
            $display("  T4 power meter         : %0d failures", e_pwr);
            $display("  T5 discrimination      : %0d failures", e_discr);
            $display("  T6 cfg_clear           : %0d failures", e_clear);
            if (e_trans != 0)
                $display("  (CIC transient, does not count: %0d differences)", e_trans);
            $display("");
            if (checked < PB_N_CH * 16)
                $display("RESULT: FAIL - far too few outputs compared (%0d).", checked);
            else if (total == 0)
                $display("RESULT: PASS");
            else
                $display("RESULT: FAIL - %0d failures in total", total);
            $display("");
            $finish;
        end
    endtask

endmodule

`default_nettype wire
